version: "3"

volumes:
  postgres_data_keycloak:
    driver: local

services:
  postgres_keycloak:
    image: postgres
    volumes:
      - postgres_data_keycloak:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
      PGPORT: 5432
    ports:
      - 5432:5432

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_SCHEMA: public
      DB_DATABASE: keycloak
      DB_ADDR: postgres_keycloak
      DB_PORT: 5432
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      PROXY_ADDRESS_FORWARDING: "True"
    ports:
      - 8080:8080
      - 8443:8443
    depends_on:
      - postgres_keycloak
