version: "3"

services:
  nginx:
    image: nginx
    network_mode: host
    volumes:
      - "./etc_nginx/:/etc/nginx/" # config + mime.types + ssl
      - "../fe/build/:/usr/share/nginx/html" # build
