micronaut:
  ssl.enabled: false # not allowed behind heroku router
  server:
    port: 8081
    host-resolution:
      protocol-header: x-forwarded-proto
      host-header: host

datasources:
  default:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
